"""add certifications table

Revision ID: e156f00ce5ab
Revises: 7649ca0d1988
Create Date: 2026-09-11 11:27:23.333354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e156f00ce5ab'
down_revision: Union[str, Sequence[str], None] = '7649ca0d1988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('issuer', sa.String(length=160), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('credential_id', sa.String(length=120), nullable=False),
    sa.Column('credential_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certifications')
    # ### end Alembic commands ###
